//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsMatikProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Discount { get; set; }
        public string Price { get; set; }
        public string WebSite { get; set; }
        public System.DateTime ListingDate { get; set; }
        public string Keyword { get; set; }
    }
}
